'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { compressImage } from '@/lib/image';

type Chemical = { chemical: string; amount: string; unit: 'kg'|'oz'|'gal'|'other' };
const initialChemical = (): Chemical => ({ chemical: '', amount: '', unit: 'kg' });
const today = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(new Date());

function Section({ number, title, detail, children }: { number: string; title: string; detail?: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#d3e0eb] bg-white p-5 shadow-[0_2px_7px_rgba(30,75,105,.03)]"><div className="mb-4 flex items-center justify-between"><h2 className="text-[17px] font-bold"><span className="mr-2 text-[15px]">{number}</span>{title}</h2>{detail && <span className="text-xs text-[#5d7390]">{detail}</span>}</div>{children}</section>; }
function PhotoTile({ file, onRemove }: { file: File; onRemove: () => void }) { const url = useMemo(() => URL.createObjectURL(file), [file]); return <div className="relative h-28 w-28 overflow-hidden rounded-xl border border-[#b9ccdc]">{file.type.startsWith('video/') ? <video src={url} aria-label="Selected pool service video" className="h-full w-full object-cover" muted playsInline /> : <img src={url} alt="Selected pool service photo" className="h-full w-full object-cover" />}<button type="button" onClick={onRemove} aria-label="Remove photo or video" className="focus-ring absolute right-1 top-1 h-7 w-7 rounded-full bg-[#17233b] text-sm text-white">×</button></div>; }

export default function TechnicianForm({ poolId, poolName }: { poolId: string; poolName: string }) {
  const supabase = useMemo(() => createClient(), []); const stripRef = useRef<HTMLInputElement>(null); const generalRef = useRef<HTMLInputElement>(null);
  useEffect(() => { stripRef.current?.removeAttribute('capture'); }, []);
  const [ph, setPh] = useState(''); const [chlorine, setChlorine] = useState(''); const [strip, setStrip] = useState<File | null>(null); const [photos, setPhotos] = useState<File[]>([]); const [chemicals, setChemicals] = useState<Chemical[]>([]); const [notes, setNotes] = useState(''); const [errors, setErrors] = useState<Record<string,string>>({}); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const validate = () => { const next: Record<string,string> = {}; const p = Number(ph), c = Number(chlorine); if (!ph || !Number.isFinite(p) || p < 0 || p > 14) next.ph = 'Enter a pH between 0 and 14.'; if (!chlorine || !Number.isFinite(c) || c < 0) next.chlorine = 'Enter a chlorine value of 0 or more.'; if (!strip) next.strip = 'A test-strip photo is required.'; chemicals.forEach((item, i) => { if ((item.chemical || item.amount) && (!item.chemical || !item.amount || Number(item.amount) < 0)) next[`chemical-${i}`] = 'Add a name and valid amount.'; }); setErrors(next); return Object.keys(next).length === 0; };
  const handleStrip = async (file?: File) => { if (file) setStrip(await compressImage(file)); };
  const handleGeneral = async (files: FileList | null) => { if (!files) return; const media = await Promise.all(Array.from(files).map(file => compressImage(file))); setPhotos(old => [...old, ...media]); };
  const save = async () => { if (!validate() || !strip) return; setSaving(true); setErrors({}); let step = 'visit record'; try {
    const status = Number(ph) < 7.2 || Number(ph) > 7.8 || Number(chlorine) < 1 || Number(chlorine) > 3 ? 'check' : 'normal';
    const visitId = crypto.randomUUID(); const { error: visitError } = await supabase.from('visits').insert({ id: visitId, pool_id: poolId, ph: Number(ph), chlorine: Number(chlorine), notes: notes.trim() || null, status }); if (visitError) throw visitError;
    const all = [{ file: strip, type: 'test_strip' as const }, ...photos.map(file => ({ file, type: 'other' as const }))]; const metadata: { visit_id:string; photo_type:string; storage_path:string }[] = [];
    step = 'photo upload';
    for (const { file, type } of all) { const path = `${visitId}/${type}/${crypto.randomUUID()}.jpg`; const { error } = await supabase.storage.from('pool-photos').upload(path, file, { contentType: file.type || 'image/jpeg', upsert: false }); if (error) throw error; metadata.push({ visit_id: visitId, photo_type: type, storage_path: path }); }
    step = 'photo record';
    if (metadata.length) { const { error } = await supabase.from('visit_photos').insert(metadata); if (error) throw error; }
    step = 'chemical record';
    const validChemicals = chemicals.filter(item => item.chemical.trim() && item.amount); if (validChemicals.length) { const { error } = await supabase.from('visit_chemicals').insert(validChemicals.map(item => ({ visit_id: visitId, chemical: item.chemical.trim(), amount: Number(item.amount), unit: item.unit }))); if (error) throw error; }
    setSaved(true);
  } catch (error) { console.error(error); const detail = error instanceof Error ? error.message : (typeof error === 'object' && error && 'message' in error && typeof error.message === 'string' ? error.message : 'Please try again.'); setErrors({ form: `Could not save the ${step}. ${detail}` }); } finally { setSaving(false); }
  };
  if (saved) return <main className="min-h-screen px-4 py-4 sm:py-8"><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-[620px] flex-col items-center justify-center rounded-3xl bg-white p-8 text-center shadow-soft"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-[#e3f7eb] text-3xl text-[#1b9453]">✓</div><h1 className="text-3xl font-bold text-ink">Visit Saved!</h1><p className="mt-2 text-[#5d7390]">Everything has been recorded.</p><div className="mt-8 flex w-full max-w-xs flex-col gap-3"><a href={`/pool/${poolId}`} className="focus-ring flex min-h-14 items-center justify-center rounded-xl bg-blue px-6 font-bold tracking-wide text-white shadow-soft hover:bg-blue/90 transition-colors">BACK TO POOL</a><a href="/admin" className="focus-ring flex min-h-14 items-center justify-center rounded-xl border border-[#c5d5e3] px-6 font-bold tracking-wide text-[#5d7390] hover:bg-[#f7fafc] transition-colors">VIEW ALL VISITS (ADMIN)</a></div></div></main>;
  return <main className="min-h-screen px-4 py-4 sm:py-8"><div className="mx-auto max-w-[620px]"><header className="rounded-2xl bg-navy px-5 py-5 text-white shadow-soft"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue text-xl font-bold">≈</div><span className="text-lg font-bold">{poolName}</span></div><h1 className="mt-6 text-sm font-normal">Hello Wayan!</h1><p className="mt-1 text-2xl text-[#c9dfef]">{today}</p></header><form onSubmit={e => { e.preventDefault(); void save(); }} className="mt-4 space-y-4">
    <Section number="①" title="Water Test"><div className="grid grid-cols-2 gap-2.5"><label className="rounded-xl border border-[#c5d5e3] p-3"><span className="block text-sm font-bold text-[#4e6179]">pH</span><input aria-label="pH" inputMode="decimal" type="number" min="0" max="14" step="0.1" value={ph} onChange={e => setPh(e.target.value)} className="focus-ring mt-1 w-full border-0 p-0 text-3xl font-bold text-[#9aa5b5] outline-none" placeholder="7.4" /><span className="mt-2 block text-[11px] text-[#5d7390]">Ideal 7.2 – 7.8</span></label><label className="rounded-xl border border-[#c5d5e3] p-3"><span className="block text-sm font-bold text-[#4e6179]">Chlorine (ppm)</span><input aria-label="Chlorine ppm" inputMode="decimal" type="number" min="0" step="0.1" value={chlorine} onChange={e => setChlorine(e.target.value)} className="focus-ring mt-1 w-full border-0 p-0 text-3xl font-bold text-[#9aa5b5] outline-none" placeholder="2.0" /><span className="mt-2 block text-[11px] text-[#5d7390]">Ideal 1.0 – 3.0</span></label></div>{(errors.ph || errors.chlorine) && <p className="mt-3 text-sm text-red-600">{errors.ph || errors.chlorine}</p>}<div className="mt-5 flex items-center justify-between"><h3 className="text-sm font-bold">Test Results Photo</h3><span className="text-xs text-[#5d7390]">required</span></div><input ref={stripRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e => { void handleStrip(e.target.files?.[0]); }} />{strip ? <div className="relative mt-2 overflow-hidden rounded-xl border border-[#a6bed0]"><img src={URL.createObjectURL(strip)} alt="Water test strip" className="h-48 w-full object-cover" /><button type="button" onClick={() => setStrip(null)} className="absolute right-2 top-2 rounded-lg bg-[#17233b]/85 px-3 py-2 text-sm font-bold text-white">Remove</button></div> : <button type="button" onClick={() => stripRef.current?.click()} className="focus-ring mt-2 flex min-h-40 w-full flex-col items-center justify-center rounded-xl border border-dashed border-[#91abc0] bg-[#f8fafc] text-[#58758b]"><span className="text-3xl">▣</span><span className="mt-2 text-sm">Take a photo of the visual test</span><span className="mt-2 rounded-lg bg-white px-4 py-2 font-bold text-blue shadow-soft">▣ Add Test Photo</span></button>}{errors.strip && <p className="mt-2 text-sm text-red-600">{errors.strip}</p>}</Section>
    <Section number="②" title="Pool & Filter Photos" detail={`${photos.length} ${photos.length === 1 ? 'item' : 'items'}`}><input ref={generalRef} type="file" accept="image/*,video/*" capture="environment" multiple className="hidden" onChange={e => { void handleGeneral(e.target.files); e.currentTarget.value = ''; }} />{photos.length > 0 && <div className="mb-3 flex flex-wrap gap-2">{photos.map((file, i) => <PhotoTile key={`${file.name}-${i}`} file={file} onRemove={() => setPhotos(old => old.filter((_, index) => index !== i))} />)}</div>}<button type="button" onClick={() => generalRef.current?.click()} className="focus-ring flex h-28 w-28 flex-col items-center justify-center rounded-xl border border-dashed border-[#91abc0] bg-[#f8fafc] text-[#58758b]"><span className="text-2xl">⊙</span><span className="mt-2 text-xs font-bold">Add Photo or Video</span></button><p className="mt-3 text-xs text-[#5d7390]">Take photos or videos of the pool, filters, or equipment.</p></Section>
    <Section number="③" title="Chemicals Added" detail="required"><div className="space-y-2">{chemicals.map((item, index) => <div key={index} className="grid grid-cols-[minmax(0,110px)_minmax(0,1fr)_70px_32px] gap-2 sm:grid-cols-[minmax(0,1fr)_78px_78px_32px]"><input aria-label={`Chemical ${index + 1} name`} value={item.chemical} onChange={e => setChemicals(old => old.map((row, i) => i === index ? {...row, chemical: e.target.value} : row))} placeholder="Chemical" className="focus-ring min-h-11 rounded-lg border border-[#c5d5e3] px-3 text-sm" /><input aria-label={`Chemical ${index + 1} amount`} type="number" min="0" step="0.1" value={item.amount} onChange={e => setChemicals(old => old.map((row, i) => i === index ? {...row, amount: e.target.value} : row))} placeholder="Amount" className="focus-ring min-h-11 rounded-lg border border-[#c5d5e3] px-2 text-sm" /><select aria-label={`Chemical ${index + 1} unit`} value={item.unit} onChange={e => setChemicals(old => old.map((row, i) => i === index ? {...row, unit: e.target.value as Chemical['unit']} : row))} className="focus-ring min-h-11 rounded-lg border border-[#c5d5e3] bg-white px-1 text-sm"><option>kg</option><option>oz</option><option>gal</option><option>other</option></select><button type="button" aria-label="Remove chemical" onClick={() => setChemicals(old => old.filter((_, i) => i !== index))} className="focus-ring text-xl text-[#5d7390]">×</button>{errors[`chemical-${index}`] && <p className="col-span-4 -mt-1 text-xs text-red-600">{errors[`chemical-${index}`]}</p>}</div>)}</div><button type="button" onClick={() => setChemicals(old => [...old, initialChemical()])} className="focus-ring mt-3 min-h-10 font-bold text-blue">＋ Add Chemical</button></Section>
    <Section number="④" title="Additional Notes" detail="optional"><textarea aria-label="Additional notes" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Anything worth noting..." rows={3} className="focus-ring w-full resize-y rounded-xl border border-[#c5d5e3] p-3 text-base outline-none" /></Section>
    {errors.form && <div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{errors.form}</div>}<button type="submit" disabled={saving} className="focus-ring min-h-14 w-full rounded-xl bg-blue font-bold tracking-wide text-white shadow-soft disabled:cursor-wait disabled:opacity-60">{saving ? 'SAVING…' : 'SAVE VISIT'}</button>
  </form></div></main>;
}
